### PR TITLE
Implemented 8ball feature

### PR DESCRIPTION
**Pull request by NrdyBhu1**

### CODE REVIEW

**Comment by Nalin-Angrish** [comment]
So how should one use it in the server?

**Comment by NrdyBhu1** [comment]
@Nalin-2005 I think `8ball should I do this stuff` would work. tbh I actually didn't really get how the utils.py works.  
One more thing is that to check if stuff works, I can't use my bot token and run on localhost.

**Comment by Nalin-Angrish** [comment]
The `format_info` function in `_utils.py` formats the responses and includes any dynamic information required.

**Comment by NrdyBhu1** [comment]
Ahh, I see, I understood, but is there any way I can run in localhost for testing new features?

**Comment by Nalin-Angrish** [comment]
Run `chat_test.py`

**Comment by NrdyBhu1** [comment]
Well, that yes :+1:  , but what about other things lol, like running a bot with bot token

**Comment by Nalin-Angrish** [comment]
for that you can probably create a dummy server, app and token and test on it

**Comment by NrdyBhu1** [comment]
Well, I tried but
```sh
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from ext.bot import TOKEN, client as bot
  File "/home/bhuvan/Programming/nrdybhu1/The2020CoderBot/ext/bot.py", line 8, in <module>
    from .chat import predict
  File "/home/bhuvan/Programming/nrdybhu1/The2020CoderBot/ext/chat.py", line 23, in <module>
    w = nltk.word_tokenize(pattern)
  File "/home/bhuvan/.local/lib/python3.8/site-packages/nltk/tokenize/__init__.py", line 130, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/bhuvan/.local/lib/python3.8/site-packages/nltk/tokenize/__init__.py", line 107, in sent_tokenize
    tokenizer = load("tokenizers/punkt/{0}.pickle".format(language))
  File "/home/bhuvan/.local/lib/python3.8/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "/home/bhuvan/.local/lib/python3.8/site-packages/nltk/data.py", line 875, in _open
    return find(path_, path + [""]).open()
  File "/home/bhuvan/.local/lib/python3.8/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/home/bhuvan/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

**Comment by Nalin-Angrish** [comment]
Oh. I forgot to include it. Open a python console and type 
```python
import nltk
nltk.download("punkt")
```
This generally happens when you use nltk for the first time. You might also need to download "wordnet" the same way.

**Comment by NrdyBhu1** [comment]
Ok that works, thanks :+1:

**Comment by NrdyBhu1** [comment]
I get errors again
```sh
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/bhuvan/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/bhuvan/Programming/nrdybhu1/The2020CoderBot/ext/bot.py", line 86, in on_message
    response = predict(message.content)
  File "/home/bhuvan/Programming/nrdybhu1/The2020CoderBot/ext/chat.py", line 78, in predict
    intent_data = classify(message)
  File "/home/bhuvan/Programming/nrdybhu1/The2020CoderBot/ext/chat.py", line 60, in classify
    model.set_tensor(input_details[0]['index'],input_data)
  File "/home/bhuvan/.local/lib/python3.8/site-packages/tensorflow/lite/python/interpreter.py", line 572, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Dimension mismatch. Got 94 but expected 93 for dimension 1 of input 0.
```

**Comment by Nalin-Angrish** [comment]
Try re-training the model. Because I never saw that message previously.

**Pull request closed without merging**
